name: Deploy backend
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - run: npm ci
      - run: npm run build

      - name: Upload backend bundle
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "dist/**,package.json,package-lock.json,prisma/**"
          target: "/var/www/justicrm/backend"

      - name: Configure, migrate, seed, start
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            cd /var/www/justicrm/backend
            # записываем .env
            cat > .env << 'EOF'
            ${{ secrets.ENV_FILE }}
            EOF
            # 1) ставим зависимости с dev (нужно для seed.ts)
            npm ci
            # 2) миграции
            npx prisma migrate deploy
            # 3) сидим админа
            npm run seed
            # 4) чистим dev-зависимости
            npm prune --omit=dev
            # 5) перезапуск/запуск pm2
            pm2 restart justicrm-backend || pm2 start dist/server.js --name justicrm-backend